### ISSUE TITLE
Long usernames exceed file size

### ISSUE THREAD

**Issue by YetAnotherMinion** [YetAnotherMinion/Banners#1]
This user's name is very small because it was very long. There should probably be some limit as to how small to make it.
![divyanshusharmaece12](https://cloud.githubusercontent.com/assets/8005290/8804594/022c2910-2f9b-11e5-9a61-aaf7b31a168a.png)

live version:
![long user](http://code-abbey-banner.appspot.com/banner/divyanshusharmaece12)

**Comment by YetAnotherMinion** [comment]
I think that some resizing looks ok but it has to have a limit. Changed so that user names can be about 12 characters long at default size (maximum fonts size 14), and can grow to about 16-18 (minimum font size 12) before begin truncated.

See 176e83e0a59c057291690bbd5723fc99f38ab2e1

**Comment by RodionGork** [comment]
Yes, that sounds quite well!

Do I understand correctly that short names will also use font size 14, not larger? (it would be good, I think)

**Comment by YetAnotherMinion** [comment]
Yes size 14 font is the max, I edited above comment to clear it up.
