### ISSUE TITLE
API shoud return rank as integer

### ISSUE THREAD

**Issue by RodionGork** [YetAnotherMinion/Banners#3]
Otherwise it would be necessary to use clumsy names for template images.

**Comment by RodionGork** [comment]
I've added the field `rankNumber`, starting with `0`. Hope this will do?

**Comment by YetAnotherMinion** [comment]
Sounds good. I had a clumsy dictionary key lookup such that I could validate possible keys then map to an enum for the rank. Now we can make things a little cleaner. I'll add the changes

**Comment by YetAnotherMinion** [comment]
Changed, and new images are now live.
